### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by pablo-arantes** [alchemistry/flamel#24]
Hi flamel team,

Thank you for your work on flamel, it's a great tool. We are trying to use for our system, and we are getting the following issue:

_Traceback (most recent call last):
  File "/home/aakash/anaconda3/envs/afe/bin/flamel", line 8, in <module>
    sys.exit(main())
  File "/home/aakash/anaconda3/envs/afe/lib/python3.9/site-packages/flamel/flamel.py", line 109, in main
    workflow.run(skiptime=args.equiltime, uncorr=args.uncorr,
  File "/home/aakash/anaconda3/envs/afe/lib/python3.9/site-packages/alchemlyb/workflows/abfe.py", line 235, in run
    self.read(use_FEP, use_TI)
  File "/home/aakash/anaconda3/envs/afe/lib/python3.9/site-packages/alchemlyb/workflows/abfe.py", line 144, in read
    column_names = u_nk_list[0].columns.values.tolist()
IndexError: list index out of range_

Following the command line that we are using to run the alchemical free energy calculations:

**flamel -a AMBER -p mdnvt_prod_ -f 10 -g -j result.csv -m MBAR -n dE -o out_data -q csv -r 3 -s 0 -t 298 -v  -w**

Can you, please, help us in this issue?

Thank you.

Best,

Pablo

**Comment by xiki-tempula** [comment]
Many thanks for the issue. I wonder if I could have the input file so I could have a test? Thanks.

**Comment by pablo-arantes** [comment]
Hi,

Thank you for your reply. Follow the file that we are using.

Thank you.
[mdnvt_prod_1.out.zip](https://github.com/alchemistry/flamel/files/10197196/mdnvt_prod_1.out.zip)

**Comment by pablo-arantes** [comment]
Hi, I've changed everything as you suggested and I'm having the following issue:

**11962 MBAR energies are > 0.0 kcal/mol
Error reading u_nk from ./mdnvt_prod_8.out.
Traceback (most recent call last):
  File "/home/aakash/anaconda3/envs/afe/lib/python3.9/site-packages/alchemlyb/workflows/abfe.py", line 121, in read
    u_nk = self._extract_u_nk(file, T=self.T)
  File "/home/aakash/anaconda3/envs/afe/lib/python3.9/site-packages/alchemlyb/parsing/amber.py", line 419, in extract_u_nk
    extracted = extract(outfile, T)
  File "/home/aakash/anaconda3/envs/afe/lib/python3.9/site-packages/alchemlyb/parsing/__init__.py", line 27, in wrapper
    dict_with_df = func(outfile, T, *args, **kwargs)
  File "/home/aakash/anaconda3/envs/afe/lib/python3.9/site-packages/alchemlyb/parsing/amber.py", line 347, in extract
    mbar_time = [
  File "/home/aakash/anaconda3/envs/afe/lib/python3.9/site-packages/alchemlyb/parsing/amber.py", line 348, in <listcomp>
    file_datum.t0 + (frame_index + 1) * file_datum.dt * file_datum.ntpr
TypeError: unsupported operand type(s) for +: 'NoneType' and 'float'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/aakash/anaconda3/envs/afe/bin/flamel", line 8, in <module>
    sys.exit(main())
  File "/home/aakash/anaconda3/envs/afe/lib/python3.9/site-packages/flamel/flamel.py", line 109, in main
    workflow.run(skiptime=args.equiltime, uncorr=args.uncorr,
  File "/home/aakash/anaconda3/envs/afe/lib/python3.9/site-packages/alchemlyb/workflows/abfe.py", line 235, in run
    self.read(use_FEP, use_TI)
  File "/home/aakash/anaconda3/envs/afe/lib/python3.9/site-packages/alchemlyb/workflows/abfe.py", line 128, in read
    raise OSError(msg) from exc
OSError: Error reading u_nk from ./mdnvt_prod_8.out.**

Thank you again.

**Comment by xiki-tempula** [comment]
Interesting, I wonder if I can have this file `mdnvt_prod_8.out`? Thanks.

**Comment by pablo-arantes** [comment]
Sure. Follow the file. Thank you!
[mdnvt_prod_8.out.zip](https://github.com/alchemistry/flamel/files/10197848/mdnvt_prod_8.out.zip)

**Comment by xiki-tempula** [comment]
@pablo-arantes Thanks. Do you mind pull the latest version of alchemlyb? I think it should be fixed now.

**Comment by xiki-tempula** [comment]
Ok, I think it just means that the folder `out_data` doesn't exist. I will make a fix. In the mean time, if you create the folder yourself, I think it would run.

**Comment by xiki-tempula** [comment]
I think all of the problems has been fixed in this issue.
