### ISSUE TITLE
Value Error

### ISSUE THREAD

**Issue by pallavsen007** [alchemistry/flamel#27]
Hi Flamel developers,
Have started uisng alchemlyb but due to sheer complexity have resorted to using flamel. However, with every BAR data I use I get a error like this Traceback (most recent call last):
  `Traceback (most recent call last):
  File "/home/pallav/anaconda3/envs/alchemlyb/bin/flamel", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/pallav/anaconda3/envs/alchemlyb/lib/python3.11/site-packages/flamel/flamel.py", line 200, in main
    workflow.run(
  File "/home/pallav/anaconda3/envs/alchemlyb/lib/python3.11/site-packages/alchemlyb/workflows/abfe.py", line 270, in run
    self.read(use_FEP, use_TI)
  File "/home/pallav/anaconda3/envs/alchemlyb/lib/python3.11/site-packages/alchemlyb/workflows/abfe.py", line 166, in read
    index_list = sorted(
                 ^^^^^^^
  File "/home/pallav/anaconda3/envs/alchemlyb/lib/python3.11/site-packages/alchemlyb/workflows/abfe.py", line 168, in <lambda>
    key=lambda x: column_names.index(
                  ^^^^^^^^^^^^^^^^^^^

`
Following is the command:

flamel -a GROMACS -d lambdas/ -f 10 -g -i 50 -j result.csv -m BAR -n dE -o out_data -p lambda -q xvg -r 3 -s 1000 -t 310 -v -w

Can you, please, help us in this issue?

Thank you.

**Comment by xiki-tempula** [comment]
Sorry this issue somehow escaped my mind. Do you still have the data that causes the issue?

**Comment by pallavsen007** [comment]
Hi there, it was sorted out. Even I do not remember it. Thanks a lot.
